FROM node:16
WORKDIR /app
#COPY package*.json ./
#COPY ./ .

#COPY ./scripts/start.sh /app
#RUN ls
#RUN chmod +x ./scripts/start.sh
#RUN chmod +x ./scripts/hold.sh
RUN chmod 777 /root
#RUN chmod 777 /app
CMD ./scripts/start.sh
