on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: set Workspace
        uses: actions/checkout@v2
        with:
          repository: ''

      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2.1.4
        with:
          cdk_subcommand: 'synth'
          working_dir: 'Backend'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          AWS_DEFAULT_REGION: 'us-west-1'

      - name: Get AWS Account ID
        id: get_account_id
        run: |
          echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV
      
      - name: cdk bootstrap
        uses: youyo/aws-cdk-github-actions@v2.1.4
        with:
          cdk_subcommand: 'bootstrap'
          cdk_stack: 'aws://$AWS_ACCOUNT_ID/us-west-1'
          working_dir: 'Backend'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          AWS_DEFAULT_REGION: 'us-west-1'

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2.1.4
        with:
          cdk_subcommand: 'deploy'
          working_dir: 'Backend'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          AWS_DEFAULT_REGION: 'us-west-1'    