on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Set Workspace
        uses: actions/checkout@v2
        with:
          repository: ''

      - name: Run cdk synth
        uses: youyo/aws-cdk-github-actions@v2.1.4
        with:
          cdk_subcommand: 'synth'
          working_dir: 'Backend'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-1'
      
      - name: Run cdk bootstrap
        uses: youyo/aws-cdk-github-actions@v2.1.4
        with:
          cdk_subcommand: 'bootstrap'
          cdk_stack: 'aws://696039535494/us-west-1'
          working_dir: 'Backend'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-1'

      - name: Run cdk deploy
        uses: youyo/aws-cdk-github-actions@v2.1.4
        with:
          cdk_subcommand: 'deploy'
          working_dir: 'Backend'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-1'    